;METADATA=(Diff=true, UseCommands=true)
[/Script/GameplayTags.GameplayTagsSettings]
ImportTagsFromConfig=True
WarnOnInvalidTags=True
ClearInvalidTags=False
AllowEditorTagUnloading=True
AllowGameTagUnloading=False
FastReplication=False
bDynamicReplication=False
InvalidTagCharacters="\"\',"
NumBitsForContainerSize=6
NetIndexFirstBitSegment=16
+GameplayTagList=(Tag="Character.Action.Attack",DevComment="")
+GameplayTagList=(Tag="Character.Action.AttackHitCheck",DevComment="")
+GameplayTagList=(Tag="Character.Action.Dead",DevComment="")
+GameplayTagList=(Tag="Character.Action.Hit",DevComment="")
+GameplayTagList=(Tag="Character.Action.LockOnSlide",DevComment="")
+GameplayTagList=(Tag="Character.Action.Roll",DevComment="")
+GameplayTagList=(Tag="Character.State.IsAttacking",DevComment="")
+GameplayTagList=(Tag="Character.State.IsHit",DevComment="")
+GameplayTagList=(Tag="Character.Weapon.Katana",DevComment="")
+GameplayTagList=(Tag="Character.Weapon.None",DevComment="")
+GameplayTagList=(Tag="Character.Weapon.Sword",DevComment="")
+GameplayTagList=(Tag="GameplayCue.Character.AttackHit",DevComment="")
+GameplayTagList=(Tag="GameplayCue.Hit.Back",DevComment="")
+GameplayTagList=(Tag="GameplayCue.Hit.Front",DevComment="")
+GameplayTagList=(Tag="GameplayCue.Hit.Left",DevComment="")
+GameplayTagList=(Tag="GameplayCue.Hit.Right",DevComment="")

